export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  SERVICE_TIMEOUT: 'SERVICE_TIMEOUT',
  UPSTREAM_ERROR: 'UPSTREAM_ERROR',
  BAD_REQUEST: 'BAD.REQUEST',
  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT.FOUND',
  INVALID_TOKEN: 'AUTH.INVALID_TOKEN',
  MISSING_KID: 'AUTH.MISSING_KID',
} as const;
